### ISSUE TITLE
Investigate the process of releasing serving-operator in operatorhub

### ISSUE THREAD

**Issue by houshengbo** [knative/serving-operator#157]
Find out the process to release serving-operator in operatorhub, and make it available there in-sync with the knative operator release.

**Comment by houshengbo** [comment]
We need to have two config maps: config-logging and config-observability, to be created for the serving operator.

How can we bundle or define them in the cluster service version yaml file(metadata)? @jcrossley3

**Comment by evankanderson** [comment]
Do we need the config maps to exist, or do we want to support configuring them with the operator, but allow them to be empty and use defaults in those cases?

**Comment by houshengbo** [comment]
@evankanderson This is exactly what I am struggling with. We would like to take advantage of the benefit to call ```sharedmain.MainWithConfig```, but it seems that we have to create ConfigMaps   of config-logging and config-observability. We can use the default values, but they have to exist.

**Comment by markusthoemmes** [comment]
can/should we adjust `MainWithConfig` to use the default if the configMap cannot be found?

**Comment by evankanderson** [comment]
It looks like you could probably adjust `GetLoggingConfig` to handle the "does not exist" case specially; it looks like monitoring doesn't do an initial fetch of the ConfigMap, so maybe only `config-logging` needs to exist?

https://github.com/knative/pkg/blob/master/injection/sharedmain/main.go#L78

**Comment by aliok** [comment]
@houshengbo We can close this ticket I think.
We already have the operators in operator hub.
See the comment https://github.com/knative/eventing-operator/issues/70#issuecomment-586640440 and https://github.com/knative/serving-operator/issues/262
