### ISSUE TITLE
support to tweak resource limits and requests for knative deployments

### ISSUE THREAD

**Issue by nak3** [knative/serving-operator#161]
limits and requests are defined like https://github.com/knative/serving-operator/blob/master/cmd/manager/kodata/knative-serving/0.8.0.yaml#L752-L758, but they are not configurable.

E.g - If we changed resources.limits by `kubectl edit deployment autoscaler -n knative-serving`, it is reverted with same reason of https://github.com/knative/serving-operator/issues/160.

**Comment by aliok** [comment]
One way of supporting this would be https://github.com/knative/serving-operator/issues/277
