### ISSUE TITLE
Check whether the operator works correctly with the latest knative serving yaml

### ISSUE THREAD

**Issue by houshengbo** [knative/serving-operator#188]
We can either create a PR-based job or periodic job to generate the latest release yaml for knative serving from master, and run the integration tests, to see if the operator works correctly with the latest knative serving.

This can facilitate the future operator release as well, since we can track the knative serving yaml on a timely fashion.

**Comment by k4leung4** [comment]
Does our integration test run the serving integration test? If so, we might want to try vendoring in serving and generate the serving yaml from the vendored version.
If we don't then generate serving master would work.
My concern is that the stability of serving on master.

In general, I like this approach, just worried about the stability of the serving master. Periodic job should be better, at least until we can determine how reliable the process is.
We should also add checks to ensure there are no unexpected deployments in the test so we can ensure we are aware of new additions.

**Comment by houshengbo** [comment]
So far I am thinking of running the integration tests of the operator only, so only generation of the serving master.

If the job passes, it means operator is ready to pick up the latest serving master to release.(should be beneficial during release)
If this job fails, it would be a good chance to look at the serving master about why it fails. It could be either the problem of operator or serving master.(help to flag the issue of instability)

**Comment by k4leung4** [comment]
sounds good to me.
