### ISSUE TITLE
Inconsisten API group

### ISSUE THREAD

**Issue by matzew** [knative/serving-operator#197]
see discussions here: https://github.com/knative/eventing-operator/issues/18

## API Group

I'd propose that we change the `apiGroup` of the serving operator from `serving.knative.dev` to `operators.knative.dev`.

Motivation:
* cleaner separation of APIs (operator API vs core serving APIs)
* simplify RBAC when operator CRDs and serving CRDs are not in the same group
* eventing operator uses `operator.knative.dev`

## KIND

the current `kind` is `KnativeServing` ... I think this makes sense... more sense than _just_ `Serving`, but IMO we should align w/ the `eventing-operator` ... which currently names it `Eventing`... perhaps that should be changed to `KnativeEventing` (as it was before) .

**Comment by markusthoemmes** [comment]
I wholeheartedly agree. `operator.knative.dev` seems fine from my perspective. I don't have a strong opinion on the kind.

**Comment by evankanderson** [comment]
+1 to `operator.knative.dev` based on trying to distinguish between _operator_ and _developer_ personas. (I had this gut feel, but credit to @mattmoor for articulating this more clearly.)
