### ISSUE TITLE
Inconsistent API names

### ISSUE THREAD

**Issue by cardil** [knative/serving-operator#222]
I'd propose that we change the `kind` of the serving operator from `KnativeServing` to `Serving`.

Also, changing others derivatives. Below full change list:

 * kind: `KnativeServing` -> `Serving`
 * listKind: `KnativeServingList` -> `ServingList`
 * plural: `knativeservings` -> `servings`
 * singular: `knativeserving` -> `serving`
 * shortNames: `ks` -> `ks` (let's leave it as `ks`, same as in eventing, sole `s` will not be understable)
 
Motivation:

* alignment with eventing name scheme, as it uses `Eventing`
* shorten names makes it easier to use and type
* community seams to settle down on shorter names, see discussion on [knative/eventing-operator#18](https://github.com/knative/eventing-operator/issues/18)
* alignment in those names will greatly simplify testing for knative productized offerings like for Red Hat's Serverless

This issue is follow up to #197

**Comment by jcrossley3** [comment]
I'm pretty sure we called it `Serving` at one time. We called it `Install` for a while, too. Here is some good discussion of some more naming tradeoffs: https://github.com/openshift-knative/knative-serving-operator/issues/17

**Comment by cardil** [comment]
Latest discussion was in here: knative/eventing-operator#18 and settled down on shorter names

**Comment by houshengbo** [comment]
@cardil I am OK with the alignment. However, after it is done, it will be a opportunity for us to think of the CR conversion when doing upgrade in future release. 
How can we convert old CRs into new CRs?

**Comment by markusthoemmes** [comment]
@houshengbo we‘ll need a reconciler for the old types that essentially create instances of the new ones based on the old ones. After a version of doing that we should be able to remove the old types and even one version later delete the code for them.

**Comment by cardil** [comment]
Closing this issue as Operations WG decided to left serving as it is now, and revert eventing to use `KnativeEventing`. Further work will be tracked under https://github.com/knative/eventing-operator/issues/18
