### ISSUE TITLE
Building the Operator Image failed, when using gcr as the docker repo

### ISSUE THREAD

**Issue by jinglundong** [knative/serving-operator#253]
## What version of Knative?

> 0.11.x
> Output of `git describe --dirty`

## Expected Behavior

As a user who wants to install serving operator, I should be able to build the operator image using gcr as the docker repo. https://github.com/knative/serving-operator#building-the-operator-image

## Actual Behavior
Build the Operator Image guide doesn't seem to cover gcr well. I probably missed something. Some clarification can prevent this type of 'human error'. 

A real example of using gcr as the docker repo may help. 

https://github.com/knative/docs/issues/1725 is a similar bug report for github. 
 
https://github.com/knative/serving-operator#building-the-operator-image

export KO_DOCKER_REPO="gcr.io/jinglun-test"
VERSION="0.11.0"
ko publish knative.dev/serving-operator/cmd/manager -t $VERSION              
2020/01/13 17:51:08 failed to publish images: importpath "knative.dev/serving-operator/cmd/manager" is not supported

**Comment by ZhiminXiang** [comment]
Can you try 
```
ko apply -f config/
```
and see if it works? (assuming you are under knative.dev/serving-operator directory)

**Comment by houshengbo** [comment]
My GOPATH is /Users/username/go.
My path for the directory knative.dev is /Users/username/go/src/knative.dev/.
The project serving-operator is saved under the directory knative.dev.
I use KO_DOCKER_REPO=docker.io/<myname> as image repo.


Building image is fine. I suspect that you did not put the source code under the directory of knative.dev.

**Comment by jinglundong** [comment]
Thanks for looking into this. It's working now. 

I didn't configured my ko correctly. I should probably file a feature request to KO, asking for better error reporting. 

I fixed this problem by reorganizing my local src directory and updating GOPATH. 
https://github.com/google/ko#determining-supported-import-paths
