### ISSUE TITLE
Installing KnativeServing CR in namespace not named knative-serving doesn't configure the APIService correctly 

### ISSUE THREAD

**Issue by whitleykeith** [knative/serving-operator#283]
**Describe the bug**
When installing the KnativeServing CR in namespace "foo", the operator also configures the APIService which always defaults to look for the knative-serving/autoscaler service. The autoscaler is not discoverable at that addresss

**Expected behavior**
The APIService is configured to look for foo/autoscaler, assuming "foo" is the namespace the KnativeServing CR has been installed into. 

**To Reproduce**
Install a KnativeServing CR into a namespace not named "knative-serving"

**Knative release version**
0.11.0

**Comment by aliok** [comment]
IMO, this is more of a question if we would like to support installing Knative in any namespace.
All the Knative documentation I can see instructs users to install things on specific namespaces.

We should do one of these:

Option A:
- We fix this problem
- We add some tests that install Knative into other namespaces and make sure things work fine
- We announce that we support this scenario

Option B:
- We don't fix this problem
- We add some validation to make sure the operator only accepts installation CRs from the specific namespace (similar to https://github.com/openshift-knative/serverless-operator/blob/master/knative-operator/pkg/webhook/knativeserving/webhook_validating.go#L140)
- We make sure operator installs Knative components into that same specific namespace
- We announce that we only support installing Knative in that specific namespace

cc @k4leung4 @houshengbo @jcrossley3

**Comment by aliok** [comment]
@markusthoemmes told me that Knative serving components should work fine in any namespace as they use `system.Namespace()`.
So, let's fix this bug and make sure we have some tests for installing Knative into other namespaces.
