### ISSUE TITLE
Support decoupling operator and installed software versions

### ISSUE THREAD

**Issue by evankanderson** [knative/serving-operator#301]
**Problem**
Today, the serving yaml is packaged and read from the `.kodata` file in the serving-operator image. This has several negative consequences:
1. It's hard to package an operator that installs nightly
2. If serving needs a cherry-pick or patch, the serving operator needs to cut a new release, too.
3. We don't have a good record of what we previously installed in the cluster.

Possibly-related issues: #277 #276 #256 

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
This is for contributors (who will be able to use the serving operator during development) and for operators.

**Exit Criteria**
1. The operator controller can deploy a **newer** version of Knative than it was built for.
2. The operator controller can **downgrade** fom a newer version of Knative to an older one
3. The operator controller can upgrade or downgrade across multiple versioned releases at one time and the operator coordinates the change.

**Time Estimate (optional):**
Probably 1-2 months for 1-2 engineers.

**Additional context (optional)**
Feature track proposal coming soon.

**Comment by evankanderson** [comment]
Proposal: https://docs.google.com/document/d/1ehd5Yx4aSottuv7FYW4JeplNULJCs7nnDfy29y3NH8k/edit#

**Comment by houshengbo** [comment]
I have the following questions regarding this feature:

**How does the operator validate the customized manifest, as a certain or a few supported versions?**


**As the manifest of serving have been split into serving-crds, serving-core, serving-hpa, net-istio, do we allow all of them customizable at the same time? If not, which ones do we allow for partial customization? How to do partial customization?**

**Comment by evankanderson** [comment]
(Moving this content to https://github.com/knative-sandbox/operator/issues/56)

/close
