### ISSUE TITLE
Initial API fields for HA control plane

### ISSUE THREAD

**Issue by pmorie** [knative/serving-operator#320]
**Problem**

Now that leader election has landed in 0.13, we should make the operator deploy an HA configuration by default.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**

Users of the operator

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):**
Simple

**Comment by evankanderson** [comment]
We had a discussion in the WG meeting on 3/3 that we don't want to double the resources for Minikube, so me may need some sort of controllable option and/or auto-sizing (i.e. "turn off HA if there is only 1 node in the cluster").

**Comment by pmorie** [comment]
I'm renaming this issue to be for the initial API changes that allow you to specify an HA installation.

**Comment by pmorie** [comment]
After discussion with @jcrossley3, i offer the following proposal:

```go
type KnativeServingSpec struct {
  // other fields omitted

  // non-nil indicates HA is requested
  HighAvailability *HighAvailability
}

type HighAvailability struct {
  // Replicas is the number of replicas to run for the HA parts of the control plane
  Replicas int
}
```

**Comment by pmorie** [comment]
part of https://github.com/knative/pkg/issues/1007
