### ISSUE TITLE
Reject ksvc creation during install process

### ISSUE THREAD

**Issue by jihuin** [knative/serving-operator#397]
**Repro steps**
1. Install knativeserving CR
2. Immediately deploy a service before the knative serving components are ready

**Expected behavior**
The ksvc creation is either 1) rejected or 2) completed and the ksvc is ready to serve.

**Actual behavior**
I saw the message `service.serving.knative.dev/helloworld-go created` without error or warning after I deployed the service `helloworld-go`, but the ready state of the ksvc stuck at `unknown` with the reason of `RevisionMissing` even after the knative serving install was completed.

When checking the logs of controller, I saw 
`{"level":"error","ts":"2020-04-12T19:08:35.843Z","logger":"controller.revision-controller","caller":"controller/controller.go:409","msg":"Reconcile error","commit":"0a30e8d","knative.dev/controller":"revision-controller","error":"failed to update deployment \"helloworld-go-vdp7v-deployment\": deployments.apps \"helloworld-go-vdp7v-deployment\" is forbidden: User \"system:serviceaccount:knative-serving:controller\" cannot update resource \"deployments\" in API group \"apps\" in the namespace \"default\"","stacktrace":"knative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:409\nknative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:395\nknative.dev/serving/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\tknative.dev/serving/vendor/knative.dev/pkg/controller/controller.go:343"}`

We should probably reject the ksvc creation before the knative serving components are ready to avoid the race condition.

**Comment by houshengbo** [comment]
I would suggest you create the ksvc after you see the CR is ready.
Have you ever tried installing serving without operator, and install the ksvc before all the serving pods are ready?

**Comment by jihuin** [comment]
I have tried installing serving without operator and deployed ksvc immediately before the serving pods were ready. The ksvc was also stuck at `RevisionMissing`.  So this is not specific to the operator installation.

I agree that the best practice is to deploy the ksvc after the serving pods are ready, but it would be great if we can avoid any confusion around this early ksvc deploying scenario. We could adjust the order of installing validatingwebhookconfiguration, mutatingwebhookconfiguration and other resources to reject the ksvc creation during the intall process.

/assign @jihuin

**Comment by markusthoemmes** [comment]
Hm, is this a bug? Modulo defaulting and whatnot from the webhook, we should absolutely be able to create a KSVC before all the knative serving component are up.

Rather than trying to enforce an order of operations, I'd rather we look at a potential bug in knative-serving here. 

/cc @mattmoor

**Comment by Cynocracy** [comment]
Regardless of whether this is a bug, do we want to validate against this race while it exists?

**Comment by mattmoor** [comment]
I wouldn't work around this without at least an issue downstream tracking this, with a repro.

**Comment by mattmoor** [comment]
That should include a pointer to any workarounds introduced so that they can be removed once fixed.

**Comment by Cynocracy** [comment]
https://github.com/knative/serving/issues/7576 includes a repro (or at least a human readable description of one). Essentially it's 
  * create a cluster
  * ko apply -f config/
  * kubectl create a ksvc
  * boom, you're stuck

Does adding a TODO: unwind when https://github.com/knative/serving/issues/7576 is resolved (and the back-edge in the serving issue) sound reasonable to close this out?

**Comment by mattmoor** [comment]
I think the main thing for me was just making sure we had tracking for the issue being worked around, so yeah I think so.  thanks, Jon.

**Comment by Cynocracy** [comment]
No problem, Matt, thanks for your comments, it's nice to know that this is an unintended edge-case we intend to fix :)
