### ISSUE TITLE
Operator should be released to gcr.io/knative-releases/github.com/knative

### ISSUE THREAD

**Issue by trshafer** [knative/serving-operator#6]
Currently the ./hack/release.sh deploys to quay.io.

**Comment by yu2003w** [comment]
Could this be configured with environment variable before build?
The default value could be gcr.io.

**Comment by houshengbo** [comment]
@yu2003w In terms of official release, they are all put under gcr.io/knative-releases/...
However, you can build image locally and push them anywhere you like, as long as you specify KO_DOCKER_REPO env var on your local machine.
