### ISSUE TITLE
Stop automatic create cr

### ISSUE THREAD

**Issue by vincent-pli** [knative/serving-operator#61]
After `operator` installation, it will create `cr` automatic if it not existed.
So if I want to customize the `cr`, for example, add the `Registry` attribute, what should i do?
Remove the original `cr` and create again?

So could we add a `flag` to let customer decide if automatic create or not.

**Comment by jcrossley3** [comment]
You should be able to edit/patch the CR and the operator will detect that it changed and re-apply the deployments to pick up your desired images.

No doubt this behavior will evolve and I expect we'll do away with the auto-create. You can follow the design discussion here: https://github.com/knative/serving-operator/issues/39

**Comment by vincent-pli** [comment]
@jcrossley3  thanks.
