### ISSUE TITLE
Run smoke test via prow / per PR

### ISSUE THREAD

**Issue by greghaynes** [knative/serving-operator#7]
Now that we have a repo with code we need some CI :)

Create a new CI job which runs the in-tree smoke test using the GKE infrastructure.

**Comment by greghaynes** [comment]
hah we don't have prow watching so I can't assign (#8)

**Comment by houshengbo** [comment]
There are four basic tests available in test-infra, and we can trigger them by adding following into the knative config yaml.
  knative/serving-operatior:
    - build-tests: true
    - unit-tests: true
    - integration-tests: true
    - go-coverage: true

I am not sure about what the smoke tests intend to do here. Knative serving is the only module that is using smoke test as a custom job.

@greghaynes What do we plan to add into the smoke tests?
Are the available four type of tests not enough so far?

**Comment by greghaynes** [comment]
I think integration tests would include smoke test. Maybe we can add just enough to get all of those test types passing. Then we can update tests/e2e to be able to run in our gke environment and pass under integration-tests?

**Comment by houshengbo** [comment]
I think firstly we can get the framework of PR builds ready for this repo.
Then, in terms of what tests need to be added, how to set up, tear down can be added later in the scripts by our implementations.

I can start by creating presubmit-tests.sh, so that operator can get into the test framework.
