### ISSUE TITLE
Replace client.Client to do the resource queries and creations

### ISSUE THREAD

**Issue by houshengbo** [knative/serving-operator#71]
We need to replace client.Client in controller-runtime to do the following queries:
```
Get v1.Node by namespace
Get deployment by namespace and name
List schema.GroupVersionKind by namespace
List certain kinds, with apiVersion, by namespace
Create namespace
```

Where we use them?
Check: https://github.com/knative/serving-operator/blob/master/pkg/reconciler/knativeserving/openshift/openshift.go#L335

or
https://github.com/knative/serving-operator/blob/master/pkg/reconciler/knativeserving/minikube/minikube.go#L42

**Comment by houshengbo** [comment]
To create namespace, we do as below:
```
nsSpec := &v1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: ns}}
_, err := clientset.Core().Namespaces().Create(nsSpec)
```

To get node, we can do as below:
```
	node, err := client.CoreV1().Nodes().Get(hostname, metav1.GetOptions{})

```

**Comment by houshengbo** [comment]
I suppose we need to use `DynamicClientSet` as in knative serving to access the GroupVersionKind.
Not sure of it so far.

**Comment by k4leung4** [comment]
Here is an example of using the dynamic client.

https://github.com/knative/serving/blob/master/pkg/reconciler/autoscaling/kpa/scaler.go#L231

Hope this helps

**Comment by houshengbo** [comment]
@k4leung4 That is for the gvr, GroupVersionResource.
We need GroupVersionKind. Not sure if they can be converted to each other. GroupVersionResourcei s the only interface available in DynamicClientSet.

**Comment by yu2003w** [comment]
Perform decency validation also needs clientset to query deployment, service, pods in specified namespaces.

**Comment by houshengbo** [comment]
We can resolved this issue with the refactoring in https://github.com/knative/serving-operator/pull/146
