### ISSUE TITLE
Add prow to monitor issues / etc

### ISSUE THREAD

**Issue by greghaynes** [knative/serving-operator#8]
We don't have prow watching our repo at all so we can't /assign, etc

**Comment by houshengbo** [comment]
It looks like we need to setup multiple prow jobs in test-infra, so that the PR can be built and verified.

**Comment by houshengbo** [comment]
I think we can assign now, after the bot has the write access.

**Comment by greghaynes** [comment]
That is what I meant by this issue - get prow listening to commands/etc
